name: DK_Vis_Nor

on:
  push:
    paths:
      - '.github/workflows/dk_vis_nor.yml'
  #  pull_request:
  #    branches: [ "main" ]
  #    paths:
  #      - .github/workflows/dk_vis_nor.yml
  #      - '**/pom.xml'
  workflow_dispatch:

  schedule:
    - cron: '0,9,19,29,39,49,59 * * * *'

jobs:
  dk-vis-nor-bot:
    runs-on: windows-latest

    steps:
      - name: checkout current
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: bot/slave-repo

      - name: checkout private
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SOURCE_REPO }}
          ref: main
          token: ${{ secrets.PAT }}
          path: bot/slot-checker

      - name: trigger bot
        shell: bash
        run: |
          java -version
          mvn -v
          cd bot
          cd slot-checker
          mvn -B clean test \
          -Dtest="VisitingVisaNorthTest" \
          -DAPP_URL=$APP_URL \
          -DUSERNAME=$U_N \
          -DPASSWORD=$P_W \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          echo "Current working directory"
          pwd
          echo "Tree view starts here"
          tree
          echo "Tree view ends here...."
          if [ -f target/value.txt ]; then
            echo "File exists"
          else
            echo "Exiting with error: NO SLOTS AVAILABLE."
            exit 1
          fi
        env:
          PLAYWRIGHT_BROWSER_ARGS: --no-sandbox
          APP_URL: ${{secrets.DK_APP_URL}}
          U_N: ${{secrets.DK_IN_NORTH_V_UN_00}}
          P_W: ${{secrets.DK_IN_NORTH_V_PW_00}}

      - name: send email
        if: success()
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.FROM_EMAIL_USERNAME }}
          password: ${{ secrets.FROM_EMAIL_PASSWORD }}
          subject: ${{ secrets.EMAIL_SUBJECT }}
          to: ${{ secrets.DK_IN_NORTH_V_CC_00 }}
          bcc: ${{ secrets.DK_IN_NORTH_V_BCC_00 }}
          from: The Big D
          body: file://bot/slot-checker/target/value.txt

          #${{secrets.EMAIL_BODY}}

      - name: Upload target
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: target
           retention-days: 2
           path: |
             ${{ github.workspace }}/bot/slot-checker/target
