name: IT_Tou_Sou

on:
  push:
    paths:
      - '.github/workflows/it_tou_sou.yml'
  workflow_dispatch:

  schedule:
    - cron: '0,9,19,29,39,49,59 * * * *'

jobs:
  it-tou-sou-bot:
    runs-on: windows-latest

    steps:
      - name: checkout current
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: bot/slave-repo

      - name: checkout private
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SOURCE_REPO }}
          ref: main
          token: ${{ secrets.PAT }}
          path: bot/slot-checker

      - name: trigger bot
        shell: bash
        run: |
          java -version
          mvn -v
          cd bot
          cd slot-checker
          mvn -B clean test -Dtest="TVSTest" \
          -DAPP_URL=$APP_URL \
          -DUSERNAME=$U_N \
          -DPASSWORD=$P_W \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          if [ -f slot-checker/target/value.txt ]; then
            echo "File exists"
          else
            echo "Exiting with error: NO SLOTS AVAILABLE."
            exit 1
          fi
        env:
          PLAYWRIGHT_BROWSER_ARGS: --no-sandbox
          APP_URL: ${{secrets.IT_APP_URL}}
          U_N: ${{secrets.IT_UK_SOUTH_T_UN_00}}
          P_W: ${{secrets.IT_UK_SOUTH_T_PW_00}}

      - name: send email
        if: success()
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.FROM_EMAIL_USERNAME }}
          password: ${{ secrets.FROM_EMAIL_PASSWORD }}
          subject: Italy - ${{ secrets.EMAIL_SUBJECT }}
          to: ${{ secrets.NL_UK_SOUTH_T_CC_00 }}
          bcc: ${{ secrets.NL_UK_SOUTH_T_BCC_00 }}
          from: The Big D
          body: file://target/value.txt
          #${{secrets.EMAIL_BODY}}

      # - name: Upload target
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: target
      #     retention-days: 2
      #     path: |
      #       ${{ github.workspace }}/target
